### ISSUE TITLE
top cities for goo goo dolls

### ISSUE THREAD

**Issue by livinglife2x** [aws-samples/amazon-lex-bi-bot#1]
![image](https://user-images.githubusercontent.com/20022657/55280406-83de9600-52e2-11e9-9993-cb2813ea6e22.png)

**Comment by livinglife2x** [comment]
![image](https://user-images.githubusercontent.com/20022657/55280424-b25c7100-52e2-11e9-8743-4d62d1955c5b.png)

**Comment by bryost** [comment]
Hi, I tried this and it seems to work fine.  Did you do step 5 of the install process successfully?  I am suspecting that your {event_name} slot was never refreshed from the database.

**Comment by livinglife2x** [comment]
That seems to be the issue, thanks for the help!
