### ISSUE TITLE
Report

### ISSUE THREAD

**Issue by livinglife2x** [aws-samples/amazon-lex-bi-bot#2]
I would like generate a PDF/EXCEL report for the results from the bibot. Could you guide me on implementing that?

**Comment by bryost** [comment]
Hi @sonukick, can you elaborate a little?  What would be the use case?  Would you ask BiBot to send the results in PDF or Excel form as an email attachment?

**Comment by livinglife2x** [comment]
I am looking for a functionality like this, Lex generating a http link carrying the csv/pdf file. 
Once I have the results for my query, I would like to generate a csv file out of them and give a link where user can download them directly.

User: give me list of customers living in state of California

Lex: Your report can be found here:
 http://www.report.com/cust-in-california.csv

**Comment by livinglife2x** [comment]
Found temporary solution. 
Route your files to S3 and share the link.
